<template>
  <div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <v-container align-center justify-left >
   <p style="font-weight: 400;">Deikho by IDEATION - TERMS OF USE</p>
<p style="font-weight: 400;">These terms of use (the "Terms") constitute a legally binding agreement between you IDEATION together with its affiliates and subsidiaries. DEIKHO (as defined below), the website(s), browser extensions, and/or mobile applications for mobile devices (the "Site") (collectively the "Service"). By accessing or using the Service, you signify that you have read, understood, and agree to be bound by this Terms of Use Agreement ("Agreement") and to the collection and use of your information as set forth in the Deikho Privacy Policy at (https://www.Deikho.com/privacypolicy), whether or not you are a registered user of the Service. This Agreement applies to you, and all other visitors, users, and others who access the Service from time to time ("Users").</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">USE OF THE SERVICE</p>
<p style="font-weight: 400;">You hereby represent and warrant to us that you are at least thirteen (13) years of age or above, are resident in a Service Location, and are capable of entering, performing and adhering to these Terms and that you agree to be bound by the following terms and conditions. While individuals under the age of thirteen (13) may utilize the Service and/or the Site, they shall do so only with the involvement &amp; guidance of their parents and/or legal guardians, under such Parent/Legal guardians registered Subscription account. You agree to register prior to commencing your use of the Service or services of the Site and provide your details including but not limited to complete name, age, email address, and contact telephone number.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">You also represent that you are an individual and not a corporation.</p>
<p style="font-weight: 400;">The Service reserves the right, at its discretion, to change, modify, add, or remove portions of these Terms at any time by posting the amended Terms. Please check these Terms periodically for changes. Your continued use of the Service after the posting of changes constitutes your binding acceptance of such changes and any so amended Terms.</p>
<p style="font-weight: 400;">Commercial Uses. The use of the Service, the Site or any Content for commercial purposes is unauthorized and may constitute infringement. You agree not to use the Service for any of the following commercial purposes without our written consent:</p>
<p style="font-weight: 400;">Selling access to the Service; or Selling or placing advertisements, sponsorship, or promotions for the Service and any of the Content without prior approval; or</p>
<p style="font-weight: 400;">Operating promotions, contests, or sweepstakes in connection with any of the Content offered on the Service or the Service itself.</p>
<p style="font-weight: 400;">Please contact us at (support.Deikho@IDEATIONtec.com) if you would like to discuss partnership or commercial ventures with us.</p>
<p style="font-weight: 400;">By connecting to the Service with a third-party service, you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials for that service.</p>
<p style="font-weight: 400;">Your responsibility for your Subscription Account. You may never use another User&rsquo;s Subscription account without permission. When creating your Subscription account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your Subscription account, and you must keep your account password secure. You must notify IDEATION immediately of any breach of security or unauthorized use of your Subscription account by contacting us at (support.Deikho@IDEATIONtec.com). IDEATION will not be liable for any loss or damage caused by any unauthorized use of your Subscription account. You may control your User profile under your Subscription account and how you interact with the Service by using the settings page on the Site.</p>
<p style="font-weight: 400;">You may use the Service solely in accordance with the terms and conditions of this Agreement and all applicable laws, rules, and regulations, including without limitation the laws of the Service Location from which you access the Service. You acknowledge and agree that certain Content or certain features of the Service may not be available to you depending on your location, and that IDEATION may add or remove any Content from the Service, any features of the Service, or discontinue the Service, at any time, is IDEATION&rsquo;s sole and absolute discretion.</p>
<p style="font-weight: 400;">Service Rules. You agree not to engage in any of the following prohibited activities unless expressly permitted by IDEATION or made available as a public feature of the Service: (i) copying, distributing, or disclosing any part of the Service in any medium, including without limitation by any automated or non-automated "scraping"; (ii) transmitting spam, chain letters, or other unsolicited email; (iii) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Service; (iv) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents through the Service; (vii) collecting or harvesting any personally identifiable information, including but not limited to Subscription account names, from the Service; (viii)</p>
<p style="font-weight: 400;">using the Service for any commercial solicitation purposes; (ix) impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity; (x) interfering with the proper working of the Service; (xi) accessing any Content on the Service through any technology or means other than those provided or authorized by the Service; (xii) bypassing the measures we may use to prevent or restrict access to the Service, including without limitation features that prevent or restrict use or copying of any Content or enforce limitations on use of the Service or the Content therein; or (xiii) knowingly using or attempting to use a fraudulent Payment Method.</p>
<p style="font-weight: 400;">Changes to the Service. We may, without prior notice and at our sole discretion, change, modify, discontinue, enhance, add or remove any Content, any part of the Site, or of the Service, or any provision of these Terms, in whole or in part, at any time; we may stop providing the Service or any of the features of the Site or the Service, to you or to Users generally; or create usage limits for the Service.</p>
<p style="font-weight: 400;">We may permanently or temporarily terminate or suspend your access to the Service without notice and liability for any reason, including if in our sole determination you violate any provision of this Agreement, or for no reason. Upon termination for any reason or no reason, you continue to be bound by this Agreement.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">DEIKHO SUBSCRIPTION SERVICES TERMS AND CONDITIONS</p>
<p style="font-weight: 400;">As part of the Service, IDEATION may offer paid weekly subscriptions (a "Subscription") to features of the Service that allow Users to access and Stream video Content on a subscription video on-demand (SVOD) basis ("DEIKHO by IDEATION"). By subscribing to or otherwise using the Service, you expressly agree to the DEIKHO Subscription Services Terms and Conditions set forth in this Section ("Subscription Terms"). If you do not agree to, or wish to abide by these Subscription Terms, you may not continue to access or use the Service, and you must immediately cease any and all use of the Service.</p>
<p style="font-weight: 400;">Eligibility. You may use the Service only if you can form a binding contract with IDEATION, and only in compliance with this Agreement and all applicable laws, rules and regulations. The Service may be accessed only in Pakistan (a &ldquo;Service Location&rdquo;). If you are not located in a Service Location, as determined by IDEATION in its sole discretion, you are not eligible to subscribe to or otherwise access or use the Service. Any access to or use of the Service outside the Service Locations is expressly prohibited. You acknowledge and agree that IDEATION may immediately suspend or terminate your access to the Service if IDEATION believes, in its sole discretion, that you are not located within a Service Location. For the time being a number of countries which might normally be included as a Service Location, are for a number of reasons, excluded. We&rsquo;re sorry, but if you live (or would like to access the Service on your travels) in either Sudan, Syria or Iran, you can&rsquo;t just yet. We&rsquo;ll let you know if and when that changes.</p>
<p style="font-weight: 400;">Intellectual Property. (a) As between you and IDEATION, the Service, the Site and the Content are all owned and/or controlled under license by IDEATION, its licensors and content and technology providers, and are protected by applicable domestic and international copyright laws. As used herein, "Content" means: (1) any and all motion pictures, programming, and any other audio visual content, images, animations, artwork, copy or information; and (2) any and all other human readable audio and/or visual elements, regardless of the form or format, accessible via the Services. Any and all underlying patentable or copyrightable elements (or elements protectable as trade secrets or otherwise under intellectual property laws) related to the Service or the Content, including without limitation, source code, script, object code, software, protocols, algorithms, computer programs, data and other sets of statements and instructions contained in the Service, Site, Content and/or any features of the Service will be considered the property of IDEATION for the purposes of this Agreement ("IDEATION IP").</p>
<p style="font-weight: 400;">(b) IDEATION, DEIKHO by IDEATION and all related registered and/or unregistered trademarks, trade names, and/or service marks ("IDEATION Marks") are the property of IDEATION and/or its affiliates or subsidiaries. Certain characters, logos, names and images incorporated by IDEATION on the Site and/or the Content are also protected as registered or unregistered trademarks, trade names and/or service marks and are the property of their respective owners. The IDEATION Marks may not be used without the express permission of IDEATION.</p>
<p style="font-weight: 400;">CONTENT RATINGS AND CLASSIFICATION. MOST CONTENT AVAILABLE ON THE SITE IS RATED ACCORDING TO GUIDELINES ESTABLISHED BY THE MOTION PICTURE ASSOCIATION OF AMERICA) I.E. G, PG, 15, R) OR TELEVISION RATINGS/CONTENT ADVISORIES. HOWEVER, SOME CONTENT MAY NOT BE RATED, AND MAY CONTAIN GRAPHIC VIOLENCE, SEXUAL CONTENT AND MATURE THEMES. SUCH CONTENT MAY NOT BE SUITABLE FOR ALL VIEWERS.</p>
<p style="font-weight: 400;">Parental Controls. Worried about little ones seeing something they shouldn't? Worry not. For your peace of mind, we have Subscription related, easy-to-use parental controls on the Service. These enable you to control the type and class of Content available and accessible on each and every device under your Subscription. For more information on the DEIKHO by Cinepax parental controls, go to the settings page on the Site.</p>
<p style="font-weight: 400;">Streaming Content. Accessing the Content available on the Service for any purpose or in any manner other than Streaming (as defined below) is expressly prohibited. &ldquo;Stream&rdquo; or &ldquo;Streaming&rdquo; means a contemporaneous digital transmission of an audiovisual work via the Internet from the Service to a User&rsquo;s device in such a manner that the data is intended for real-time viewing and not intended to be copied, stored, permanently downloaded, or redistributed by the User. We may at times allow certain Content to be downloaded by you on a temporary basis, to be stored on the hard-drive of your device(s) for a certain period of time, so you can enjoy DEIKHO by IDEATION even when you might not be able to access the internet in order to Stream. This doesn&rsquo;t change anything though. The Content is still ours, still subject to the license below (and the rest of this Agreement) and we can of course change our mind at any time.License. Subject to the terms and conditions of this Agreement (including these Subscription Terms) and the payment by you of all applicable Subscription Fees (as defined below), during the term of your Subscription, IDEATION grants you a non-exclusive, limited, non-transferable, freely revocable license to Stream the video Content made generally available on the Service in a Service Location solely for your personal, non-commercial use and solely as permitted by the features of the Service. You may use five (5) separate devices under your Subscription to use and access the Service &ndash; so, your laptop, an iPad, your iPhone, and still two (2) more left to play with - with two (2) concurrent Streams at any one time. This means you can watch the latest episode of your favourite drama TV shows on one device, while the children watch Frozen for the tenth time on their iPad.</p>
<p style="font-weight: 400;">This license does not include any rights (and you agree not) to: (1) archive, permanently download, reproduce, distribute, modify, perform, broadcast, display, license, sell, resell, lend, lease, rent or otherwise use, access, or commercially use the Site, Content or any other material or information contained therein; (2) collect or use any information, data, listings, or descriptions for any reason; (3) create derivative works from the Site, Content or any other materials or information contained therein; (4) download or copy information of any third party; (5) use data mining, robots, or other data gathering and extraction tools; (6) distribute, transfer, or post any Content on any third party website, online service or other media; (7) modify, adapt, copy or otherwise create derivative works from or translate any part of the Site or Content; (8) reverse engineer, decompile or disassemble the Site or Content, or otherwise attempt to obtain access to the IDEATION IP (as defined above); (9) remove or alter any copyright, trade mark or other proprietary notice contained in the Services, Site, or Content. Except as provided herein, you may not frame or utilize framing techniques to use, surround or enclose the Site or Content or any trademarks, service marks, logo, or other proprietary information (including: images, text, page layout, or form) of IDEATION and/or its affiliates or subsidiaries or Content providers without IDEATION's express written consent. You may not use any meta-tags or any other "hidden text" utilizing the name of the Site, IDEATION and/or its affiliates, subsidiaries or Content providers, or any trade names or trademarks or other copyrighted materials relating thereto, without the express written consent of IDEATION.</p>
<p style="font-weight: 400;">PAYMENT INFORMATION AND BILLING POLICIES</p>
<p style="font-weight: 400;">Recurring Subscription. By registering for the Service, you agree to the pricing terms as set forth on the Site, as we may update them from time to time. You agree to pay all fees due for your weekly Subscription to the Service (&ldquo;Subscription Fees&rdquo;) on or around the date you register for the Service (unless you participate in a free trial or other Promotion if provided), and you hereby authorize IDEATION to charge your Payment Method (as defined below) for all such Subscription Fees as and when they fall due. You acknowledge and agree that your Subscription will automatically renew for additional periods on or around each renewal date after you registered for the Service (each a "Renewal Date"), unless you cancel your Subscription prior to the applicable Renewal Date. You further authorize IDEATION to charge your Payment Method the Subscription Fees on or around each Renewal Date. IDEATION may add new services for additional fees and charges, or amend fees and charges for existing services, at any time in its sole discretion. Any change to our pricing or payment terms shall become effective in the billing cycle following notice of such change to you as provided in this Agreement.</p>
<p style="font-weight: 400;">No Commitment. Don&rsquo;t worry, there is no long term commitment or fixed term contract. You may cancel this Agreement and thereby your Subscription via your profile on the Site at any time before a Renewal Date and before your next Subscription is due to start, and when you cancel it, If you do, your Subscription will not be automatically renewed. You can of course re-activate the Service on your Subscription at a later date. However, there are NO REFUNDS OR CREDITS for cancellation, unless required otherwise by applicable law. In the event that you or IDEATION suspends or terminates your Subscription or this Agreement, you understand and agree that you shall receive no refund, credit, or exchange for any unused time on a Subscription, any license or Subscription Fees for any portion of the Service, any Content or data associated with your Subscription, or for anything else.</p>
<p style="font-weight: 400;">Payment Method, Charges, and Taxes. All information that you provide in connection with a purchase or transaction or other monetary transaction interaction with the Service must be legitimate, accurate, complete, and current. You agree to pay all charges incurred by you and/or any other user of your credit card, debit card or other payment method used in connection with a purchase or transaction or other monetary transaction interaction with the Service (&ldquo;Payment Method&rdquo;) at the prices in effect when such charges are incurred. You will pay any applicable taxes and other fees, if any, whether now applicable or applied in the future, relating to any such purchases, transactions or other monetary transaction interactions.</p>
<p style="font-weight: 400;">Free Trial Promotions. We may, at our sole and absolute discretion, offer free trial periods of the Service and/or other promotions in connection with the Service (&ldquo;Promotion(s)&rdquo;). In the event a free trial Promotion is offered to you, you can try the Service before you buy for a pre-determined period, depending on that particular offer or trial period. However, this will still require you to input your normal registration details (such as name, address details, age and/or telephone number) as part of your Subscription. We only allow one free trial Promotion per Subscription, household, telephone number, Payment Method, name, or alter-ego, and we reserve the right to prevent you from taking advantage of such free trial Promotion if we think you have already had one.</p>
<p style="font-weight: 400;">If you&rsquo;re starting a free trial, you will still need to provide details of your chosen Payment Method but, please rest assured that no payment will be taken by us until and unless you decide to continue your Subscription once that free trial Promotion comes to an end. You can of course cancel your free trial Promotion at any time, with no further obligation, by informing us and cancelling your Subscription, but whilst you can re-activate your Subscription at any time, you will not be permitted to re-activate or re-subscribe and again benefit from a free trial Promotion.</p>
<p style="font-weight: 400;">You acknowledge and agree that the full Subscription Fees will become immediately due for your continued Subscription and access to the Service upon the expiration of any Promotion, unless you cancel your Subscription prior to the expiration of said Promotion. You agree to pay all such Subscription Fees on or around such date, and you authorize IDEATION to charge your Payment Method for all such Subscription Fees at such time.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">DEIKHO RELATED COMPETITIONS</p>
<p style="font-weight: 400;">Competition Rules. By participating in any online (or real world) DEIKHO by IDEATION competition whether on or through the Site, or on or through any social media platform (including but not limited to Facebook, Instagram, or Twitter), or on or through any other media (each, a &ldquo;Competition&rdquo;), all Competition entrants agree to be bound by the following rules (the &ldquo;Competition Rules&rdquo;) and also, as to the result of any Competition and the winner(s) of any applicable prizes, the decisions of IDEATION, which shall be final in all matters relating to that Competition, and no correspondence will be entered into.</p>
<p style="font-weight: 400;">Entry to any Competition is restricted to one entry per Subscription, per Competition. Late, illegible, incomplete, defaced or corrupt entries or entries sent through third parties will not be accepted. No responsibility can be accepted for lost entries and proof of dispatch will not be accepted as proof of receipt. Competitions are not open to employees of IDEATION and/or their immediate families and affiliated companies and subsidiaries. Competitions are not open to employees and their immediate families of any Competition sponsoring company and affiliated companies and subsidiaries.</p>
<p style="font-weight: 400;">All elements of any prize(s) are subject to availability or change, non-transferable and there are no cash alternatives. Winners may not change a prize, and/or its respective components in any way except with the prior written approval of IDEATION, which approval shall be at the sole and absolute discretion of IDEATION.</p>
<p style="font-weight: 400;">Where applicable, a prize must be used or collected within the specified time period stated or within 6 months from the date of draw &ndash; whichever is longer</p>
<p style="font-weight: 400;">IDEATION reserves the right to implement age requirements where necessary and specific age restrictions may be applicable for some Competitions. In general, winners must be 18 years of age or over, or accompanied by an adult, who is 18 years or over.</p>
<p style="font-weight: 400;">All entries must be received by the time specified, on the closing date specified, for any given Competition. The winner(s) will be drawn at random by IDEATION, from all entries received by the closing date.</p>
<p style="font-weight: 400;">In order to be eligible for prizes, the winner(s) (and guest if applicable) must release IDEATION from any and all liability, claims, demands, and causes of action for personal injury and/or damage, theft, or loss suffered in connection with the Competition or the use or acceptance of the prize or any portion thereof. Entry into the Competition constitutes the issuance of such release.</p>
<p style="font-weight: 400;">Winner(s) agree that IDEATION and its subsidiaries, affiliates, related companies and employees, and any other sponsors shall have no liability in connection with acceptance or use of any of the prizes awarded herein.</p>
<p style="font-weight: 400;">The receipt, by any winner, of any of the prize components of a Competition is conditional upon compliance with any and all laws, rules and regulations. Winners are solely responsible for all insurance, applicable taxes and for any expenses not specified in the prize description. Where prizes involve the winner(s) traveling, winner(s) (and guest if applicable) shall be required to hold a valid passport and/or other necessary travel documentation and visas and will be responsible for any and all costs in addition to the Competition prize to attend the event.</p>
<p style="font-weight: 400;">Winners authorize IDEATION to utilize their full names, city, and country of residence and other relevant information to announce Competition results via, but not limited to, IDEATION affiliated websites (including the Site), social media sites related to IDEATION and or e-newsletters. By entering the Competition, all entrants assign all rights, title and interest in all creative material uploaded onto the Site.</p>
<p style="font-weight: 400;">Events may occur which inhibit the Competition draw or the prize itself, due to circumstances beyond the control of IDEATION, in which case, IDEATION will not be held liable for such events.</p>
<p style="font-weight: 400;">The decisions of IDEATION as to the identity and/or eligibility of the final winner(s) of any prizes are final and shall be at the sole and absolute discretion of IDEATION. Winner(s) will be notified by e-mail or telephone as soon as possible after the closing date of the prize draw. Should IDEATION be unable to contact a winner or should a winner be unable to accept the prize, IDEATION reserves the right to award the prize to an alternate winner, drawn in accordance with these Competition Rules.</p>
<p style="font-weight: 400;">IDEATION reserves the right in its sole discretion to substitute any and all prizes with prizes of comparable value.</p>
<p style="font-weight: 400;">IDEATION reserves the right to disqualify any entrant and/or winner who contravene the Competition Rules.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">PROPRIETARY RIGHTS</p>
<p style="font-weight: 400;">The Service and all materials therein or transferred thereby, including, without limitation, the Content, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, and any/all Intellectual Property Rights related thereto, are the exclusive property of IDEATION and its licensors. You agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from the Service and/or any of the Content. Use of the Service and/or the Content for any purpose not expressly permitted by this Agreement is strictly prohibited.</p>
<p style="font-weight: 400;">Confidential Information. You agree not to access, or try to access, any information through the Site that does not pertain to you and which you are not properly authorized to receive. You agree that if you should access information about another individual or entity, or otherwise receive information you are not authorized to receive, or if you become aware that someone else has accessed or attempted to access information that such person was not authorized to receive, you will immediately cease such unauthorized access, notify IDEATION of the unauthorized access, and reasonably assist IDEATION in identifying and correcting the circumstances which permitted such unauthorized access. You will keep confidential all information you receive concerning another individual or entity, will not use such information, will return such information to IDEATION immediately, will not transmit it to any other person or entity and will not reproduce or distribute it in any electronic or other form.</p>
<p style="font-weight: 400;">Copyright Notice. If you are of the honest belief that any content appearing on the Site constitutes copyright infringement in any way, shape, or form, please forward the following information to (support.Deikho@IDEATIONtec.com):</p>
<p style="font-weight: 400;">Your name, address, telephone number, and email address; A description of the copyrighted work that you claim has been infringed; The exact URL or a description of where the alleged infringing material is located; A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; and, a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner&rsquo;s behalf.</p>
<p style="font-weight: 400;">Privacy Policy. We care about the privacy of all of our Users, and yes, that means you and your personal information and private data. You understand that by using the Service you consent to the collection, use and disclosure of your personally identifiable information and aggregate data as set forth in the IDEATION Privacy Policy at (http://www.Deikho.com/privacypolicy).</p>
<p style="font-weight: 400;">User Submissions. IDEATION is pleased to hear from its customers and welcomes your comments regarding our products and services. These comments should only be submitted to (support.Deikho@IDEATIONtec.com) or perhaps one of the mailboxes available to users of the Site provided from time to time for that purpose. All remarks, suggestions, ideas, graphics, or other information communicated to IDEATION through the Site for any reason (each, a "Submission") will forever be the property of IDEATION. IDEATION will not be required to treat any Submission as confidential, and will not be liable for any ideas for its business (including without limitation, product or advertising ideas) and will not incur any liability as a result of any similarities between your Submission and any future IDEATION products, services or operations. Without limitation, IDEATION will have exclusive ownership of all present and future existing rights to the Submissions of every kind and nature, everywhere. IDEATION will be entitled to use the Submission for any commercial or other purpose whatsoever, without compensation to you or any other person sending the Submission. You acknowledge that you are responsible for whatever material you submit, and you, not IDEATION, have full responsibility for the message, including its legality, reliability, appropriateness, originality, and copyright. You acknowledge and agree that neither IDEATION nor any of its licensees, successors or assigns has now, or will have in the future, any duty or liability, direct or indirect, vicarious, contributory or otherwise, with respect to the infringement or protection of any copyright in and to your Submission, and that IDEATION and its licensees, successors or assigns are not responsible for the loss, deletion, failure to store or misdelivery of any feedback submitted.</p>
<p style="font-weight: 400;">Policy for Individuals under the age of 13. IDEATION encourages the responsible use of the internet by children together with their parents and to that end, IDEATION does not knowingly collect or use any personally identifiable information submitted or posted to the Services and/or the Site from individuals under the age of 13, except as may be applicable in order to respond on a one-time basis to a specific request for information.</p>
<p style="font-weight: 400;">Security. IDEATION cares about the integrity and security of your personal information. However, we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.</p>
<p style="font-weight: 400;">Links to and from Third Party Websites. (a) The Site may contain links to other internet websites, including without limitation social media websites. IDEATION does not verify, warrant, endorse or take responsibility for the availability, accuracy, completeness, quality, practices or policies of any such third party website. IDEATION does not make any representations or warranties as to the security of any information (including, without limitation, credit card and other personal information) you might be requested to give to any third party, and you irrevocably waive any claim against us with respect to any such third party website.</p>
<p style="font-weight: 400;">(b) You are not permitted to link the Site or any of the Content to or from any third party website without the prior written consent of IDEATION, which consent shall be at the sole and absolute discretion of IDEATION.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">LEGAL</p>
<p style="font-weight: 400;">Indemnity. You agree to defend, indemnify and hold harmless IDEATION and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney&rsquo;s fees) arising from: (i) your use of and access to the Service, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement, including without limitation your breach of any of the representations and warranties contained herein; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable law, rule or regulation; (v) your User content or any Submission that is submitted via your Subscription account or otherwise; (vi) your use of any Content in violation of local law; or (vii) any other party&rsquo;s access and use of the Service with your unique username, password or other appropriate security code.</p>
<p style="font-weight: 400;">DISCLAIMER OF WARRANTIES. THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, IDEATION, ITS SUBSIDIARIES, AND ITS LICENSORS DO NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE SERVICE.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">IDEATION DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICE OR ANY HYPERLINKED WEBSITE OR SERVICE.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">LIMITATION OF LIABILITY. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL IDEATION, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, THAT RESULT FROM THE USE OF, OR INABILITY TO USE, THE SERVICE. UNDER NO CIRCUMSTANCES WILL IDEATION BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICE OR YOUR SUBSCRIPTION ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
<p style="font-weight: 400;">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IDEATION ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF OUR SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.</p>
<p style="font-weight: 400;">The Service is controlled and operated by IDEATION from its facilities in the United Arab Emirates. IDEATION makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions including from within any other Service Location do so at their own volition and are entirely responsible for compliance with all applicable local laws and regulations.</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">GENERAL</p>
<p style="font-weight: 400;">&nbsp;</p>
<p style="font-weight: 400;">Miscellaneous. These Terms set forth the nature and extent of your relationship with IDEATION as it pertains to the Service, including the Site and/or the Content. These Terms are binding upon and inure to the benefit of IDEATION and you, and IDEATION&rsquo;s successors and assigns, if any.</p>
<p style="font-weight: 400;">Assignment. This Agreement, your obligations, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by IDEATION without restriction. Any attempted transfer or assignment in violation hereof shall be null and void.</p>
<p style="font-weight: 400;">Notification Procedures and Changes to the Agreement. IDEATION may provide notifications, whether such notifications are required by law or are for marketing or other business related purposes, to you via email notice, written or hard copy notice, or through posting of such notice on the Site, as determined by IDEATION in our sole discretion. IDEATION reserves the right to determine the form and means of providing notifications to our Users, provided that you may opt out of certain means of notification as described in this Agreement. IDEATION is not responsible for any automatic filtering you or your network provider may apply to email notifications we send to the email address you provide us. IDEATION may, in its sole discretion, modify or update this Agreement from time to time, and so you should review this page periodically to check for any recent modifications or updates. When we change the Agreement in a material manner, we will update the &lsquo;last modified&rsquo; date at the bottom of this page. Your continued use of the Service after any such change constitutes your acceptance of the new Terms. If you do not agree to any of these terms or any future Terms, do not use or access (or continue to access) the Service.</p>
<p style="font-weight: 400;">Entire Agreement/Severability. This Agreement, together with any amendments and any additional agreements you may enter into with IDEATION in connection with the Service, shall constitute the entire agreement between you and IDEATION concerning the Service. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect.</p>
<p style="font-weight: 400;">Export Restrictions. You agree that you will comply with all applicable export laws, restrictions and regulations of the U.S. Department of Commerce, the U.S. Department of Treasury and any other U.S. or foreign agency or authority. You agree not to export or re-export, or allow the export or re-export of the Services, the Site, or the Content, in violation of any such law, restriction or regulation.</p>
<p style="font-weight: 400;">Force Majeure. IDEATION will not have any liability to you for any delay or non-performance of its obligations under this Agreement, to the extent that such delay or non-performance is attributable to an Event of Force Majeure (as hereinafter defined). For the purposes of this Agreement, "Event of Force Majeure" will mean an act of God, war, riot, rebellion or civil unrest, labour dispute, or failure of facilities, networks, equipment or software, or any similar event, to the extent that such event is beyond the reasonable control of IDEATION.</p>
<p style="font-weight: 400;">No Waiver. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and IDEATION&rsquo;s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision.</p>
<p style="font-weight: 400;">Relationship. Nothing contained in this Agreement will constitute, or enable the development of a joint venture, partnership or any other employee/employer or independent contractor relationship or any other commercial relationship (except as seller and customer) between you and IDEATION.</p>
<p style="font-weight: 400;">Law. This Agreement will be governed by the laws of the Dubai International Finance Centre (&lsquo;DIFC&rdquo;), irrespective of DIFC's conflict or choice of law rules. Any action brought by you arising out of or relating to this Agreement may be brought exclusively in DIFC, and you irrevocably consent to the jurisdiction of such courts and venue.</p>
    </v-container>
  </div>
</template>
<script>
export default {
  name: "terms",

      head() {
        
    return {
      titleTemplate: "Terms and Conditions",
      meta: [
        {
          name: "Terms and Conditions",
          content:
            "Terms and Conditions"
        }
      ]
    };
  },
};
</script>
<style>
</style>